ssl_certificate /etc/nginx/certs/live/fullchain.pem;
ssl_certificate_key /etc/nginx/certs/live/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
